config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :sensors 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sensor.rb
class Sensor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
	before_action :set_sensor, only: [:name, :serial_number, :model, :brand, :status, :comment, :image]
  def index
    @sensors = Sensor.all
  end

  def show
    @sensor = Sensor.find(params[:id])
  end

  def new
    @sensor = Sensor.new
  end

  def create
    @sensor = Sensor.new(sensor_params)
    @sensor.save
    redirect_to sensors_path
  end

  def edit
    @sensor = Sensor.find(params[:id])
  end

  def update
    @sensor = Sensor.find(params[:id])
    @sensor.update(sensor_params)
    @sensor.save
    redirect_to sensor_path(@sensor)
  end

  def destroy
    @sensor = Sensor.find(params[:id])
    @sensor.destroy

    redirect_to sensors_path
  end

  private

  def set_sensor
    @sensor = Sensor.find(params[:id])
  end

  def sensor_params
  params.require(:sensor).permit(:name, :serial_number, :model, :brand, :status, :comment, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChmEquipment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sensors/_form.html.erb
<%= simple_form_for(sensor) do |f| %>
  <div>
    <%= f.input :name %>
  </div>
  <div>  
    <%= f.input :serial_number %>
  </div>
  <div>
    <%= f.input :model %>
  </div>
  <div>  
    <%= f.input :brand %>
  </div>
  <div>  
    <%= f.input :status %>
  </div>
  <div>  
    <%= f.input :comment %>
  </div>
  <div>  
    <%= f.input :image %>
  </div> 
  <%= f.submit class: "btn btn-primary mt-1"%>
<% end %>

app/views/sensors/edit.html.erb
<h1>Edit a Sensor</h1>
<%= render "form", sensor: @sensor %>

<%= link_to 'Back to list', sensors_path, class: "btn btn-primary mt-1"%>

app/views/sensors/index.html.erb
<h1>My sensors</h1>
<% @sensors.each do |sensor| %>
	<div class='m-1'>
		<p><%= link_to sensor.name, sensor_path(sensor)%></p>
		<p><%= "#{sensor.model}, #{sensor.brand}, #{sensor.serial_number}" %></p>
	</div>
<% end %>


<%= link_to 'Add a new sensor', new_sensor_path, class: "btn btn-primary mt-1"%>

app/views/sensors/new.html.erb
<h1>Add a Sensor</h1>
<%= render "form", sensor: @sensor %>

<%= link_to 'Back to list', sensors_path, class: "btn btn-primary mt-1"%>

app/views/sensors/show.html.erb
<h2><%= @sensor.name %></h2>
<p><%= @sensor.model %></p>
<p><%= @sensor.brand %></p>
<p><%= @sensor.serial_number %></p>
<% if @sensor.status %>
	<p>Status: Working</p>
<% else %>
	<p>Status: Not Working</p>
<% end %>
<p><%= @sensor.serial_number %></p>
<p><%= @sensor.comment %></p>
<img src=<%= @sensor.image %> alt="">
<br>
<%= link_to "Delete #{@sensor.name}",
            sensor_path(@sensor),
            method: :delete,
            data: { confirm: "Are you sure?" },
            class: "btn btn-danger mt-1" %>

<br>

<%= link_to 'edit', edit_sensor_path, class: "btn btn-danger mt-1" %>

<br>

<%= link_to 'Back to list', sensors_path, class: "btn btn-primary mt-1"%>